### ISSUE TITLE
New Feature: Host Modify

### ISSUE THREAD

**Issue by schwartx** [schwartx/octoproxy#7]
## Description

The Host Modify feature would merge the functionality of both [host_rewrite](https://github.com/schwartx/octoproxy/issues/4#issue-1755931224) and [host_route](https://github.com/schwartx/octoproxy/issues/5#issue-1756125755). Users will no longer need to configure these options separately, as they can now be set together within the `host_modify` configuration option.

The Host Modify feature would allow users to add a client configuration option named `host_modify`. This would be followed by a toml file path that contains a list of host modify rules.

## The File Format Example:

The `host_modify` file is a toml file with the following format:
```toml
["example.com"]
rewrite = "127.0.0.1"
backend = "local1"

["google.com"]
rewrite = "127.0.0.1"
backend = "local1"
```

- Each section represents a host entry, such as `example.com`, google.com. Each domain entry can have 2 configuration options: `rewrite` and `backend`. The `rewrite` option specifies the IP address or hostname to which the host would be rewritten, and the `backend` option specifies the backend to which the request would be forwarded. 

- For each section, if either the `rewrite` or `backend` option is not set, the corresponding functionality would be ignored. If all options are not set, the entire section would be ignored.
```toml
["example.com"]
rewrite = "127.0.0.1"
backend = "local1"

# this section would be ignored.
["google.com"]
```

In the future, there might be additional functionality options added.
